added mypy

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -2,7 +2,7 @@
 
 if [ -z "$VIRTUAL_ENV" ]
 then
-    echo "error: VIRTUAL_ENV not set" >&2
+    echo "error: VIRTUAL_ENV is not set" >&2
     exit 11
 fi
 
@@ -24,11 +24,20 @@ else
     echo "pyright check: ok"
 fi
 
+mypy $(git ls-files '*.py' | grep -v contrib)
+if [ $? -ne 0 ]
+then
+    echo "error: mypy check failed" >&2
+    exit 41
+else
+    echo "mypy check: ok"
+fi
+
 pylint $(git ls-files '*.py' | grep -v contrib)
 if [ $? -ne 0 ]
 then
     echo "error: pylint check failed" >&2
-    exit 41
+    exit 51
 else
     echo "pylint check: ok"
 fi
@@ -37,7 +46,7 @@ flake8 $(git ls-files '*.py' | grep -v contrib)
 if [ $? -ne 0 ]
 then
     echo "error: flake8 check failed" >&2
-    exit 51
+    exit 61
 else
     echo "flake8 check: ok"
 fi
